**In the beginning, this notebook is a summary of the Numpy Library. I prepared it to help anyone study this library, and I wish everyone success.**

In [1]:
# ! pip install numpy

In [2]:
import numpy as np

##### Trigonometric functions

In [3]:
# Python deal with trigonometric functions(sin,cos,tan,...) as redian  not degree
a = np.sin(30) # sin (30) = -0.9880316240928618 not 0.5
b = np.cos(60) # cos (60) = -0.9524129804151563 not 0.5
print(a,b)

# First we must return it to radian
arad = np.sin(30*np.pi/180)
brad = np.cos(60*np.pi/180)
print(arad,brad)

# Or use deg2rad function in numpy
a1 = np.sin(np.deg2rad(30))
b1 = np.cos(np.deg2rad(60))
print(a1,b1)

-0.9880316240928618 -0.9524129804151563
0.49999999999999994 0.5000000000000001
0.49999999999999994 0.5000000000000001


In [4]:
# round function in numpy
rnd = np.round(3.256489) 
rnd1= np.round(3.256489,5)
print(rnd)
print(rnd1)

3.0
3.25649


In [5]:
# Mod in numpy
md = np.mod(20,7)
print(f'Mod = {md}')

Mod = 6


##### Matrices

In [6]:
# First create matrix from list  by use array
# 1_dim
lis = [1,2,3,4,5]
mat1d = np.array(lis)
# Or mat = np.array([1,2,3,4,5])
print('mat1d')
print(mat1d)

# 2_dim
lis2d = [[1,2,3],[4,5,6],[7,8,9]] # 3*3
mat2d = np.array(lis2d)
print('mat2d')
print(mat2d)

# 3_dim
lis3d = [[[1,2],[3,4]],[[5,6],[7,8]]] # 2 * 2 * 2
mat3d = np.array(lis3d)
print('mat3d')
print(mat3d)

mat1d
[1 2 3 4 5]
mat2d
[[1 2 3]
 [4 5 6]
 [7 8 9]]
mat3d
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# way2 by range function
mat2d = np.array([range(x,x+3) for x in [2,4,6]])
print(mat2d)

# we can difine name about each element in matrix
mat = np.array([('x',3,4.2),('y',4,5.3),('z',5,6.4)],dtype=[('name','U5'),('number','i2'),('value','f4')])
print(mat)

[[2 3 4]
 [4 5 6]
 [6 7 8]]
[('x', 3, 4.2) ('y', 4, 5.3) ('z', 5, 6.4)]


In [8]:
# Make empty matrix
emp = np.empty((3,2))
print(emp)

[[4.89366280e-310 0.00000000e+000]
 [2.14321575e-312 2.22809558e-312]
 [2.46151512e-312 5.68175493e-322]]


In [9]:
# Make a matrix that is all zeros
matz1d = np.zeros(8) # 1*N
print(matz1d)
#matz2d = np.zeros((3,2)) # N*M
#matz3d = np.zeros((2,2,2)) # N*M*D

[0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
# Make a matrix that is all ones
mato1d = np.ones(8) # 1*N
print(mato1d)
#mato2d = np.ones((3,2)) # N*M
#mato3d = np.ones((2,2,2)) # N*M*D

[1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
# Make a matrix that is all the same number
mat = np.full((3,3),7)
print(mat)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
# Make a unit matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# Making the diagonal matrix
dig_mat = np.diag(np.array([1,2,3,4,5]))
print(dig_mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [14]:
# Making the diagonal matrix and add k row & k col with zero values at the beginning
dig_mat_k_r_c = np.diag(np.array([1,2,3,4,5]),k=2)
print(dig_mat_k_r_c)

[[0 0 1 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 4 0]
 [0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [15]:
# Obtain max value, average, std value, variance, correlation coefficient, and  min value in the matrix
# np.argmax(x) , np.argmin(x) return index_array
x = np.array([1,2,3,4,5])
np.max(x) , np.mean(x) , np.std(x) , np.var(x) , np.corrcoef(x) , np.min(x) , np.argmax(x) , np.argmin(x)

(5, 3.0, 1.4142135623730951, 2.0, 1.0, 1, 4, 0)

In [16]:
"""
Make matrix by use arange function 
"""
a = np.arange(12) # 0 ...N
b = np.arange(10,18) # x...y-1
print(a)
print(b)

dim = a.ndim # Or np.ndim(a)
print(f'dimintional = {dim}')

print(f'Type numbers {a.dtype}')

len1 = len(b)  
# len(b) == b.size   in one dimintional  -> return matrix length
print(f'matrix lenth  = {len1}')

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[10 11 12 13 14 15 16 17]
dimintional = 1
Type numbers int64
matrix lenth  = 8


In [17]:
# Make 2d matrix by use arange function
mat = np.arange(12).reshape(3,4) 
# Note in reshape must n*m = number in arange function
print(mat)

dim = mat.ndim # Or np.ndim(a)
print(f'dimintional     = {dim}')

print(f'Matrix shape    {mat.shape}')

print(f'Type numbers    {mat.dtype}')

len1 = len(mat)  
# len(mat)  -> return number of rows
print(f'matrix lenth    = {len1}')

size1 = mat.size  
# mat.size  -> return number of all elements in matrix
print(f'matrix size     = {size1}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
dimintional     = 2
Matrix shape    (3, 4)
Type numbers    int64
matrix lenth    = 3
matrix size     = 12


In [18]:
# Make 3d matrix by use arange function
mat = np.arange(36).reshape(2,6,3) 
# Note in reshape must n*m*d = number in arange function
print(mat)

dim = mat.ndim # Or np.ndim(a)
print(f'dimintional       = {dim}')

print(f'Matrix shape      {mat.shape}')

print(f'Type numbers      {mat.dtype}')

len1 = len(mat)  
# len(mat)  -> return number of layer
print(f'matrix lenth      = {len1}')

size1 = mat.size  
# mat.size  -> return number of all elements in matrix
print(f'matrix size       = {size1}')

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
dimintional       = 3
Matrix shape      (2, 6, 3)
Type numbers      int64
matrix lenth      = 2
matrix size       = 36


In [19]:
# Calculate determinde , trace diagonal for matrix
mat = np.arange(4).reshape(2,2)
print(mat)
sumdig = np.trace(mat)
# sum elements of digonal
print(sumdig) 

det = np.linalg.det(mat)
print(det)

eig = np.linalg.eig(mat)
# Compute the eigenvalues and right eigenvectors of a square array.
print(f'eigenvalues = {eig}')

[[0 1]
 [2 3]]
3
-2.0
eigenvalues = EigResult(eigenvalues=array([-0.56155281,  3.56155281]), eigenvectors=array([[-0.87192821, -0.27032301],
       [ 0.48963374, -0.96276969]]))


##### Find the inverabce of the matrix
###### $$\hat{A}^{-1}  =  \hat{adj(A) / |A| ;} \hat{|A|≠ 0} $$

In [20]:
mat = np.arange(4).reshape(2,2)

inv = np.linalg.inv(mat)
#A-1 = adj(A) / |A|; |A| ≠ 0
# inv = np.linalg.inv(mat).astype(np.int64)
print(inv) 

print(np.dot(mat,inv)) # np.dot(mat,inv) => eye matrix

[[-1.5  0.5]
 [ 1.   0. ]]
[[1. 0.]
 [0. 1.]]


##### Random function in numpy

In [21]:
nuiform_num = np.random.uniform(1,10)
# return ramdon float number between 1,10
print(f'Number  = {nuiform_num}')

nuiform_num1 = np.random.uniform(1,10,5)
# retrun array of  5 random float numbers between 1,10 
print(f'Array = {nuiform_num1}')

Number  = 9.597147614086007
Array = [4.80479788 1.30000662 9.07093873 3.94107759 5.62616877]


In [22]:
rand_mat = np.random.random((2,3))
# retrun 2-D array N row * M col contain random numbers (0 --> 1) 
print(rand_mat) 
# if we need numbers 0-->10
print('$$')
print(rand_mat*10)

[[0.21311557 0.40704664 0.33434265]
 [0.37425469 0.04037365 0.7506483 ]]
$$
[[2.1311557  4.07046637 3.34342648]
 [3.74254695 0.40373647 7.50648305]]


In [23]:
norm = np.random.normal(0,1,5)
# retrun normal distribution to z nmbers between x,y (contain ngtiv,postive number) 
print(norm)

[-3.08559839 -0.65459421 -1.27449046 -0.13032292  0.81474467]


In [24]:
num = np.random.randint(150)
# randint(150) return one number between (0-149)
print(num)

num1 = np.random.randint(5,size=6)
# randint(5,size=6) return 6 numbers from 0 to 4 and allows repetition
print(num1)

num2 = np.random.randint(5,20,size=7)
# randint(5,20,size=7) return 7 numbers from 5 to 19 and allows repetition
print(num2)

num3 = np.random.randint(0,10,(3,3))
#Returns random numbers from 0 to 10 as a two-dimensional array and allows repetition.
print(num3)

num4 = np.random.randint(0,10,(2,4,3))
#Returns random numbers from 0 to 10 as a three-dimensional array and allows repetition.
print(num4)

num5 = np.random.randint(1,60,size=25)
num6 = np.reshape(num5,(5,5))
# Or num5 = np.random.randint(1,60,size=25).reshape(5,5)

#Returns random numbers from 1 to 59 
#Then make reshape as a two-dimensional array and allows repetition.
# We need to make sure that the dimensions are correct for this
print(num6)

146
[4 2 3 2 4 0]
[12  6  6  8  6 10 12]
[[0 0 6]
 [4 3 2]
 [2 2 1]]
[[[1 0 8]
  [2 1 6]
  [2 1 4]
  [0 8 2]]

 [[4 0 1]
  [6 7 7]
  [5 7 8]
  [3 3 3]]]
[[44  3 20 35  7]
 [ 3  4 53 21 41]
 [32 53 26 17 48]
 [53 58 43 42 47]
 [19 50 17 24 34]]


In [25]:
rand1 = np.random.rand(5)
# return 1-D array contain 5 random numbers from 0-1 
print(rand1)

rand2 = np.random.rand(2,2)
# return 2-D array contain random numbers from 0-1
print(rand2)

"""rand3 = np.random.rand(2,2,2)
# return 3-D array contain random numbers from 0-1
print(rand3)"""

[0.69259706 0.88522451 0.71974031 0.81129831 0.80213068]
[[0.65916948 0.51649142]
 [0.26206289 0.25257874]]


'rand3 = np.random.rand(2,2,2)\n# return 3-D array contain random numbers from 0-1\nprint(rand3)'

In [26]:
shf = [1,2,3,4,5]
np.random.shuffle(shf)
print(shf)

[5, 1, 2, 3, 4]


In [27]:
lis = [1,2,3,4,5,6]
choic1 = np.random.choice(lis)
print(choic1)

5


##### Linespace

In [28]:
# linespace (x,y)
"""
In this case, it comes with numbers distributed evenly between x and y including. 
The number of digits, if not specified, is 50.
If it exists, we divide by it
The equation for the increase between numbers is (y - x) / 50
The equation for the increase between numbers (x,y,z) is (y - x) / z
"""
line1 = np.linspace(0,30)
print(f'Length line1 = {len(line1)}')
print(line1)
line2 = np.linspace(30,100,5)
print(f'Length line1 = {len(line2)}')
print(line2)

Length line1 = 50
[ 0.          0.6122449   1.2244898   1.83673469  2.44897959  3.06122449
  3.67346939  4.28571429  4.89795918  5.51020408  6.12244898  6.73469388
  7.34693878  7.95918367  8.57142857  9.18367347  9.79591837 10.40816327
 11.02040816 11.63265306 12.24489796 12.85714286 13.46938776 14.08163265
 14.69387755 15.30612245 15.91836735 16.53061224 17.14285714 17.75510204
 18.36734694 18.97959184 19.59183673 20.20408163 20.81632653 21.42857143
 22.04081633 22.65306122 23.26530612 23.87755102 24.48979592 25.10204082
 25.71428571 26.32653061 26.93877551 27.55102041 28.16326531 28.7755102
 29.3877551  30.        ]
Length line1 = 5
[ 30.   47.5  65.   82.5 100. ]


In [29]:
mat = np.random.randint(0,10,size=9).reshape(3,3)
print(mat)

count = np.count_nonzero(mat)
print(f'Nonzeros = {count}')

count2 = np.count_nonzero(mat>5)
print(f'Nonzeros>5 = {count2}')

c = np.count_nonzero(mat>5,axis=1)
# Works on rows and return array
print(c)

c1 = np.count_nonzero(mat<8,axis=0)
# Works on cols and return array
print(c1)

[[0 4 1]
 [1 7 4]
 [0 4 3]]
Nonzeros = 7
Nonzeros>5 = 1
[0 1 0]
[3 3 3]


In [30]:
x = np.array([[1,2,3],[4,5,6]])
flag = np.any(x>2)
print(flag)

flag1 = np.any(x>2,axis=1)
print(flag1)

flag2 = np.all(x>2)
print(flag2)

True
[ True  True]
False


In [31]:
m = np.arange(2,8)
mat = np.multiply.outer(m,m)
print(m)
print(mat)

np.multiply.accumulate(m)

[2 3 4 5 6 7]
[[ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]
 [10 15 20 25 30 35]
 [12 18 24 30 36 42]
 [14 21 28 35 42 49]]


array([   2,    6,   24,  120,  720, 5040])

In [32]:
np.add.accumulate([2, 3, 5])

array([ 2,  5, 10])

In [33]:
# hstack function
# a,b must the same number of rows
a = np.arange(4).reshape(2,2)
b = 2*np.arange(4).reshape(2,2)
print(a)
print(b)
h = np.hstack((a,b))
# Or h = np.concatenate([a,b],axis=1)
print(h)

[[0 1]
 [2 3]]
[[0 2]
 [4 6]]
[[0 1 0 2]
 [2 3 4 6]]


In [34]:
# vstack function
# a,b must the same number of cols
a = np.arange(4).reshape(2,2)
b = 2*np.arange(4).reshape(2,2)
print(a)
print(b)
v = np.vstack((a,b))
# Or v = np.concatenate([a,b],axis=0)
print(v)

[[0 1]
 [2 3]]
[[0 2]
 [4 6]]
[[0 1]
 [2 3]
 [0 2]
 [4 6]]


##### Sort Matrix
###### (def sort(a, axis=-1, kind=None, order=None):Return a sorted copy of an array.The default is 'quicksort)

In [35]:
# Example
a = np.random.randint(5,20,size=9).reshape(3,3)
# deful
print(f'a = ')
print(a)
print("***********")
b = np.sort(a)                # sort along the last axis (axis=1)
print(f'b =')
print(b)
print("***********")
# flatten returns (1, N) for np.matrix, so always use the last axis
flatten_array = np.sort(a,axis=None)
print(f'flatten_array = {flatten_array}')
print("***********")
srow = np.sort(a,axis=1) # sort evry row alone # sort along the last axis
print(f'srow =')
print(srow)
print("***********")
scol = np.sort(a,axis=0) # sort evry col alone  # sort along the first axis
print(f'scol =')
print(scol)


a = 
[[14  8 14]
 [13  7 10]
 [16 17 14]]
***********
b =
[[ 8 14 14]
 [ 7 10 13]
 [14 16 17]]
***********
flatten_array = [ 7  8 10 13 14 14 14 16 17]
***********
srow =
[[ 8 14 14]
 [ 7 10 13]
 [14 16 17]]
***********
scol =
[[13  7 10]
 [14  8 14]
 [16 17 14]]


##### Adding and subtracting matrices

In [36]:
# Must be 2 array of the same dimensions
a = np.random.randint(1,20,size=9).reshape(3,3)
b = np.random.randint(2,25,size=9).reshape(3,3)
#print(a)#print(b)
sum ,sub = a+b , a-b
print(sum)
print(sub)

[[30 25 26]
 [24 20 26]
 [21  9 29]]
[[  8  -5  -6]
 [-16  10  -2]
 [ 15  -7   1]]


In [37]:
x = 7+np.array([[1,2,3],[4,5,6]])
print(x)

[[ 8  9 10]
 [11 12 13]]


In [38]:
mat = np.array([[1,5,7],[8,9,10],[14,2,8]])
sum = mat.sum()
# Or sum = np.sum(mat)
print(sum)
sum1 = mat.sum(axis=1) # sum each row individually
sum2 = mat.sum(axis=0) # sum each col individually
print(sum1)
print(sum2)

64
[13 27 24]
[23 16 25]


##### Multiplay matrices

In [39]:
# Num * Matrix
x = np.array([[1,2,3],[4,8,9]])
#print(x) 
print(x*7)

[[ 7 14 21]
 [28 56 63]]


In [40]:
# Matrix * Matrix
# by use *    must be the same dimintional
a = np.random.randint(1,20,size=9).reshape(3,3)
b = np.random.randint(2,25,size=9).reshape(3,3)
print(a*b)

[[ 80   4 285]
 [276  44  78]
 [102  18  64]]


##### Algebraic multiplication
[<center><img src="https://www.boardinfinity.com/blog/content/images/2022/11/Your-paragraph-text--48-.jpg" width="250"></center>](Algebraic_multiplication.jpg)

In [41]:
#  Matrix * Matrix(N*c) x (c*M)=>(N*M)
# by use np.dot() function  (Algebraic multiplication)
A = np.array([[1,2,3],[4,5,6]]) # 2*3
B = np.array([[10,11],[20,21],[30,31]]) # 3*2
print('A',A)
print()
print('B',B)
print()
mul = np.dot(A,B) # 2*2
print('Result')
print(mul)

A [[1 2 3]
 [4 5 6]]

B [[10 11]
 [20 21]
 [30 31]]

Result
[[140 146]
 [320 335]]


##### Polynomials in numpy

In [42]:
# 1- Find best fit line
polynom = np.polynomial.Polynomial
x = np.array([0,20,40,60,80,100])
y = np.array([10,9,8,7,6,5]) # x,y must be the same dimintional

points,stats = polynom.fit(x,y,1,full=True) # 1 mean Equation of the first degree 
print(points) # points contain (slop , y interset)
#print(stats) 
#                        y = mx + c

7.5 - 2.5·x


In [43]:
polynom = np.polynomial.Polynomial
x = np.array([0,20,40,60,80,100])
y = np.array([10,9,8,7,6,5]) # x,y must be the same dimintional

points,stats = polynom.fit(x,y,2,full=True) # 2 mean Equation of the second degree 
print(points) # points contain (slop , y interset)
#print(stats) 
#                       y = ax^2 + bx + c

7.5 - 2.5·x + (6.49543447e-15)·x²


##### Writing equations

In [44]:
eq =  np.poly1d((-7))
eq1 = np.poly1d((-7,2))
print(eq)
print(eq1)

 
-7
 
-7 x + 2


In [45]:
eq2 = np.poly1d((-7,2,1))
print(eq2)

    2
-7 x + 2 x + 1


In [46]:
eq3 = np.poly1d((-7,2,1,3))
print(eq3)
# if we need to set value to x
res = eq3(5)
print(f'Result = {res}')

    3     2
-7 x + 2 x + 1 x + 3
Result = -817


In [47]:
# The two steps can be combined together (creating the equation, substituting)
A = np.polyval((10,5),2) # 10x + 5
print(A)

25


##### Derivation

In [48]:
# first creating equation
equation = np.poly1d((1,2,3))
print(equation)

# second dervsion it 
derv1 = np.polyder(equation) # Derivation once
# Or  derv1 = np.polyder(np.poly1d((1,2,3)))
print(derv1)

   2
1 x + 2 x + 3
 
2 x + 2


In [49]:
derv2 = np.polyder(np.poly1d((1,2,3,5)),2) # Derivation twice 
"""
x^3 + 2x^2 + 3x + 5  # equation
3x^2 + 4x + 3        # derv 1
6x + 4               # derv 2
"""
print(derv2)

 
6 x + 4


##### Integration

In [50]:
intg = np.polyint(np.poly1d((1,2,3)))
# eq = x^2 + 2x + 3
print(intg)

        3     2
0.3333 x + 1 x + 3 x


In [51]:
intg2 = np.polyint(np.poly1d((6,4)),2)
print(intg2)

   3     2
1 x + 2 x


##### Roots of the equation

In [52]:
# Define the coefficients of the third-degree polynomial
p = np.array([1, -7, 14, -8])

# Find the roots of the polynomial
roots = np.roots(p)

# Print the roots of the polynomial
print(roots)

[4. 2. 1.]


##### Read text file

In [53]:
# Text file data converted to integer data type 
#File_data = np.loadtxt("example1.txt", dtype=int) 
#print(File_data) 